export const METADATA = {
  IS_PUBLIC: 'IS_PUBLIC',
  ACTION: 'ACTION',
  MODULE: 'MODULE',
  ROLE: 'ROLE',
  CONFIDENTIAL_BODY: 'CONFIDENTIAL_BODY',
  EXCEPTION_FORMAT_ROUTES: 'EXCEPTION_FORMAT_ROUTES',
};
